packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - protobufjs
  - unrs-resolver

injectWorkspacePackages: true

overrides:
  lightningcss: 1.30.1
  react: ^19.1.0
  react-dom: ^19.1.0
