packages:
  - packages/*
  - apps/*
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
  - protobufjs
  - unrs-resolver
overrides:
  lightningcss: 1.30.1
catalog:
  "@babel/core": ^7.28.4
  "@better-auth/expo": ^1.3.28
  "@bottom-tabs/react-navigation": ^0.12.2
  "@expo/vector-icons": ^15.0.2
  "@hashgraph/sdk": ^2.76.0
  "@hono/standard-validator": ^0.1.5
  "@hono/zod-validator": ^0.6.0
  "@maca134/hono-passport": ^1.2.2
  "@neondatabase/serverless": ^1.0.0
  "@paralleldrive/cuid2": ^3.1.0
  "@react-navigation/material-top-tabs": ^7.3.8
  "@react-navigation/native": ^7.1.18
  "@rn-primitives/accordion": ^1.2.0
  "@rn-primitives/alert-dialog": ^1.2.0
  "@rn-primitives/aspect-ratio": ^1.2.0
  "@rn-primitives/avatar": ^1.2.0
  "@rn-primitives/checkbox": ^1.2.0
  "@rn-primitives/collapsible": ^1.2.0
  "@rn-primitives/context-menu": ^1.2.0
  "@rn-primitives/dialog": ^1.2.0
  "@rn-primitives/dropdown-menu": ^1.2.0
  "@rn-primitives/hover-card": ^1.2.0
  "@rn-primitives/label": ^1.2.0
  "@rn-primitives/menubar": ^1.2.0
  "@rn-primitives/navigation-menu": ^1.2.0
  "@rn-primitives/popover": ^1.2.0
  "@rn-primitives/portal": ^1.3.0
  "@rn-primitives/progress": ^1.2.0
  "@rn-primitives/radio-group": ^1.2.0
  "@rn-primitives/select": ^1.2.0
  "@rn-primitives/separator": ^1.2.0
  "@rn-primitives/slot": ^1.2.0
  "@rn-primitives/switch": ^1.2.0
  "@rn-primitives/table": ^1.2.0
  "@rn-primitives/tabs": ^1.2.0
  "@rn-primitives/toggle": ^1.2.0
  "@rn-primitives/toggle-group": ^1.2.0
  "@rn-primitives/tooltip": ^1.2.0
  "@scalar/hono-api-reference": ^0.9.9
  "@tailwindcss/postcss": ^4.1.14
  "@tanstack/react-form": ^1.23.7
  "@tanstack/react-query": ^5.90.2
  "@types/crypto-js": ^4.2.2
  "@types/mjml": ^4.7.4
  "@types/node": ^24.8.1
  "@types/nodemailer": ^6.4.17
  "@types/passport-http-bearer": ^1.0.41
  "@types/react": ~19.2.2
  ajv: ^8.17.1
  await-to-ts: ^1.0.6
  babel-preset-expo: ^54.0.4
  better-auth: ^1.3.28
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  crypto-js: ^4.2.0
  date-fns: ^4.1.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.2
  drizzle-zod: ^0.8.3
  eslint: ^9.37.0
  eslint-config-expo: ^10.0.0
  eslint-config-prettier: ^10.1.8
  expo: ^54.0.13
  expo-constants: ~18.0.9
  expo-document-picker: ~14.0.7
  expo-file-system: ~19.0.17
  expo-image: ~3.0.10
  expo-linking: ~8.0.8
  expo-navigation-bar: ~5.0.8
  expo-network: ^8.0.7
  expo-router: ~6.0.12
  expo-secure-store: ^15.0.7
  expo-status-bar: ~3.0.8
  expo-system-ui: ~6.0.7
  expo-web-browser: ~15.0.8
  hono: ^4.9.6
  hono-openapi: ^1.1.0
  ky: ^1.11.0
  lucide-react-native: ^0.545.0
  mjml: ^4.15.3
  nativewind: ^5.0.0-preview.2
  nodemailer: ^7.0.3
  postcss: ^8.5.6
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: 19.1.1
  react-dom: 19.1.1
  react-native: 0.81.4
  react-native-css: ^3.0.1
  react-native-gesture-handler: ~2.28.0
  react-native-mmkv: ^3.3.3
  react-native-pager-view: 6.9.1
  react-native-reanimated: ^4.1.3
  react-native-safe-area-context: ^5.6.1
  react-native-screens: ~4.16.0
  react-native-svg: ^15.14.0
  react-native-tab-view: ^4.1.3
  react-native-web: ^0.21.1
  react-native-worklets: ^0.6.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.14
  toastify-react-native: ^7.2.3
  ts-pattern: ^5.8.0
  turbo: ^2.6.0
  typescript: ~5.9.3
  zod: ^4.1.12
  zod-openapi: ^5.4.3
  zustand: ^5.0.8
